### ISSUE TITLE
Background not dark

### ISSUE THREAD

**Issue by KarelPeeters** [ice1000/NppExtension#2]
I don't know if this is a problem with my settings or the definitions of this project, but the background doesn't seem to be dark. A screenshot:

![image](https://user-images.githubusercontent.com/7887115/29846340-c7f7ea00-8d16-11e7-9368-9bfc1fa2a351.png)

The color is set correctly in the background styler:

![image](https://user-images.githubusercontent.com/7887115/29846352-da3ac96c-8d16-11e7-97af-94c0767a5686.png)

I'm running Notepad++ `v7.5`.

**Comment by ice1000** [comment]
In this case, you'd better choose a **dark theme**.

Try this:

![2017-08-30 12-56-50](https://user-images.githubusercontent.com/16398479/29856045-e4d3f56c-8d82-11e7-84fb-ca9e5d24d1ac.png)

**Comment by KarelPeeters** [comment]
Hmm, the background doesn't quite match:

![image](https://user-images.githubusercontent.com/7887115/29923108-9215ae34-8e58-11e7-8eb5-d8b7d4610423.png)

That can be fixed by changing the global background color, but then it doens't match the other styles. Is there no build-in way to do this per style?

**Comment by ice1000** [comment]
I'm sorry no. This is what I tried very hard and failed to do when I was working on this repo (say, set the background color for one specific language). It's really a pity.

The background color is `#2B2B2B`. Try this:

![image](https://user-images.githubusercontent.com/16398479/29951108-01427270-8ef3-11e7-9c5f-1dfd7a54f617.png)

**Comment by KarelPeeters** [comment]
Yup, that works, it's unfortunate that Npp doesn't allow this. Thanks for the help.

**Comment by vico93** [comment]
Any plans to add a light-theme version?

**Comment by ice1000** [comment]
@vpontin It's easy, simply replace all `2B2B2B` with your expected color (like `FFFFFF`) in the config xml.
if you consider the text colors are not beautiful with light background, edit the colors and open a pull-request.

Since I've removed Windows and installed Linux on my PC, maintaining this repo becomes more difficult for me. Sorry.

**Comment by vico93** [comment]
Oh, understood. Thanks!

**Comment by ice1000** [comment]
@vpontin Added kt-light.xml
