### ISSUE TITLE
Kotlin lowercase float literal

### ISSUE THREAD

**Issue by cvzi** [ice1000/NppExtension#4]
Hi, I am using the file `kt-light.xml` in Notepad++

Any chance you can add support for lowercase `f` suffix for float numbers, it works correctly for the uppercase suffix `F`:
```kotlin
val x = 1.5F // currently colored correctly
val y = 1.5f // currently not colored correctly
```

While looking into this, I found [this reference](https://kotlinlang.org/docs/reference/basic-types.html#underscores-in-numeric-literals-since-11) which says underscores are allowed in numbers, so these two should be colored the same:
```kotlin
val c = 1000000    // currently colored correctly
val d = 1_000_000  // currently not colored correctly
```

**Comment by ice1000** [comment]
I have to clarify: the notepad++'s highlighting framework has limited support for complicated (we all hope we can use regex in this case) tokens.
For the lowercase float lit, I'll take a look.
